Add pre-commit config to provide feedback on code quality before pushing
bifrostlab/llm-assistant pull request #17
Opened 2024-02-14 12:00 UTC by hungdtrn

In pre-commit config, I use the following hook 
- pre-commit hooks:
  - trailing-whitespace
  - end-of-file-fixer
  - check-byte-order-marker
  - check-added-large-files
  - check-shebang-scripts-are-executable
- ruff hook

2024-02-14 13:53 UTC, nqngo commented
Add Ruff, pre-commit plugins to the VSCode devcontainer.

Add Ruff, pre-commit to dev dependencies.

Specify pre-commit to install on post-install step.

Update from python 3.10 to python 3.12.

Ensure the poetry.lock file is now consistent with pyproject.toml.

2024-02-14 23:30 UTC, hungdtrn commented
@nqngo  I have updated devcontainer and pyproject.toml, please have a look.
Also, can you clarify "Specify pre-commit to install on post-install step"? Do you mean that I should write a hook on "post-install" event for pre-commit install?

2024-02-14 23:51 UTC, hungdtrn commented
@nqngo I realized that the changes I made had already been done last night

2024-02-15 00:14 UTC, nqngo commented
> @nqngo can you clarify "Specify pre-commit to install on post-install step"? Do you mean that I should write a hook on "post-install" event for pre-commit install?

My bad. The comment was around what has been done on my commit and not a task list. Just to clarify what I've setup.

2024-02-15 00:33 UTC, samhwang commented on poetry.lock
> +# This file is automatically @generated by Poetry 1.4.2 and should not be changed by hand.
We should all be running on Poetry 1.7.1

2024-02-15 00:37 UTC, samhwang commented on .devcontainer/post-install.sh
> +pre-commit install
add an extra line at the end for consistency

2024-02-15 01:08 UTC, samhwang requested changes
Add a few scripts in the poetry config file to run ruff, so we can also run it manually.

https://python-poetry.org/docs/cli/#run

2024-02-15 01:09 UTC, samhwang commented on .pre-commit-config.yaml
> +    - id: trailing-whitespace
We shouldn't need to run styling lints through pre-commit-hooks, that should be handled by `ruff`.

2024-02-15 01:38 UTC, samhwang commented on .pre-commit-config.yaml
> +    - id: end-of-file-fixer
We shouldn't need to run styling lints through pre-commit-hooks, that should be handled by `ruff`.

2024-02-15 02:58 UTC, samhwang commented on .devcontainer/post-install.sh
> +pre-commit install
Still needs to be updated here

```suggestion
poetry run pre-commit install
```

2024-02-15 03:52 UTC, samhwang commented on .devcontainer/post-install.sh
> +poetry run pre-commit install
Missing the extra line at the end of the file

2024-02-15 03:58 UTC, hungdtrn commented
> Add a few scripts in the poetry config file to run ruff, so we can also run it manually.
> 
> https://python-poetry.org/docs/cli/#run

Do you have any example of the custom script? I don't know why do we need to have some custom script for running ruff.

2024-02-15 04:07 UTC, samhwang commented
> Do you have any example of the custom script? I don't know why do we need to have some custom script for running ruff.

Ignore my previous comment 😓 I had a look at poetry from the `npm` world and thought we can define custom scripts so you don't have to type in `poetry run ruff check .` repeatedly.

2024-02-15 04:50 UTC, samhwang commented on pyproject.toml
> +line-length = 88
Our current Flake8 runs with 127 line length.

https://github.com/bifrostlab/llm-assistant/blob/334adcaf3abffe9f52ec4927b27df2881b2b0147/.github/workflows/python-app.yml#L34

2024-02-15 05:43 UTC, nqngo commented on pyproject.toml
> +line-ending = "auto"
set the line-ending here as "lf" to be consistent with our editor Config.

2024-02-15 08:45 UTC, samhwang approved these changes

2024-02-15 08:46 UTC, merged