refactor: move code to src
bifrostlab/llm-assistant pull request #31
Opened 2024-02-25 12:56 UTC by hungdtrn

2024-02-25 13:25 UTC, rodonguyen approved these changes

2024-02-25 22:04 UTC, samhwang commented on tests/test_litellm_proxy.py
I'd recommend rename this file into something else. Putting the name as `test_ASDF.py` and it will get picked up by unit testing tools like Pytest.

2024-02-25 22:05 UTC, samhwang commented on tests/test_litellm_proxy.py
something like `litellm_proxy_playground.py` or `litellm_scratchpad.py`

2024-02-25 22:07 UTC, samhwang commented on tests/test_litellm_proxy.py
or, for this particular file, put this in a `./playgrounds` folder, then the file is `./playgrounds/litellm_proxy.py`

2024-02-25 22:24 UTC, samhwang requested changes
see my comment

2024-02-27 08:23 UTC, rodonguyen commented on tests/test_litellm_proxy.py
Oh right, i thought it is some kind of test so...

2024-02-27 08:37 UTC, samhwang commented on litellm_uuid.txt
what's is this file and what is it doing in this pr?

2024-02-27 08:42 UTC, samhwang approved these changes

2024-02-27 08:42 UTC, merged