feat: add router settings for LiteLLM
bifrostlab/llm-assistant pull request #33
Opened 2024-03-01 14:09 UTC by rodonguyen

- Add router settings for LiteLLM

2024-03-01 22:44 UTC, samhwang requested changes

2024-03-01 22:44 UTC, samhwang commented on .gitignore
> +
- delete the extra lines, only keep 1
- can we have an explanation why this file is added here?

```suggestion
# Reason why this file is added
litellm_uuid.txt
```

2024-03-01 22:46 UTC, nqngo submitted a review, later dismissed

2024-03-01 22:46 UTC, nqngo commented on src/litellm/proxy_config.yaml
> +  routing_strategy: least-busy      # Literal ["simple-shuffle", "least-busy", "usage-based-routing", "latency-based-routing"]
Remove comments. Comment should be used to explain the codes. For everything else there is git.

2024-03-02 04:30 UTC, samhwang requested changes

2024-03-02 04:30 UTC, samhwang commented on src/litellm/proxy_config.yaml
> +litellm_params:
duplicate?

2024-03-02 04:30 UTC, samhwang commented on .gitignore
> +litellm_uuid.txt
add an extra line before each section

```suggestion

# litellm auto generated files
litellm_uuid.txt
```

2024-03-02 04:34 UTC, rodonguyen commented on src/litellm/proxy_config.yaml
> +litellm_params:
oops don't know why it happened

2024-03-02 04:35 UTC, samhwang approved these changes

2024-03-02 04:37 UTC, merged