refactor: remove litellm dependencies
bifrostlab/llm-assistant pull request #45
Opened 2024-03-09 12:03 UTC by nqngo

Remove LiteLLM as a dependency for the Discord bot as it is now running in a separate docker container.

See:

https://github.com/bifrostlab/deploy-llm-bot/pull/12

2024-03-09 12:33 UTC, samhwang requested changes
Tests broken

2024-03-09 13:16 UTC, nqngo commented
> Tests broken

Remove test, no problem. Jk let me fix it.

2024-03-09 13:53 UTC, rodonguyen commented
I don't know much about Docker stuff but it looks good XD (as long as it works)

2024-03-15 12:34 UTC, nqngo commented
Per last week discussion, the test is removed from github actions. Will need to rewrite the test to mock to ensure we can test functionality without calling the actual LiteLLM proxy.

2024-03-15 13:36 UTC, samhwang requested changes

2024-03-15 13:36 UTC, samhwang commented on tests/test_discord_bot_llm.py
these changes aren't needed

2024-03-15 13:36 UTC, samhwang commented on Dockerfile.test_ollama
these changes aren't needed

2024-03-15 22:21 UTC, samhwang approved these changes

2024-03-15 22:21 UTC, merged